### ISSUE TITLE
org.postgresql.util.PSQLException: ERROR: syntax error at or near "-"

### ISSUE THREAD

**Issue by coolrb** [openraven/magpie#572]
I am trying to run magpie with postgres v 14.7 hosted in aws, scanning aws components. However, it always gives following exception:
Caused by: org.postgresql.util.PSQLException: ERROR: syntax error at or near "-"
  Position: 638
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2675)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2365)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:355)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:490)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:408)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:166)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:118)
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.extract(ResultSetReturnImpl.java:57)

**Comment by kickroot** [comment]
Sorry for the delayed response, this slipped through.  Can you provide a full stack trace?
