### ISSUE TITLE
Bug: non persistant option still uses database

### ISSUE THREAD

**Issue by JGodin-C2C** [openraven/magpie#594]
Hello OpenRaven !

## Summary

We are testing your tools, but i found that when the magpie.persist is setted as false, magpie still tries to connect to a database and thus failing. 

Here is my config.yaml

```
layers:
  enumerate:
    type: origin
    queue: default
    plugins:
      - magpie.aws.discovery
      - magpie.gcp.discovery
      - magpie.azure.discovery
  output:
    type: terminal
    dequeue: default
    plugins:
      - magpie.json
      - magpie.persist
fifos:
  default:
    type: local
policies:
  root: ~/.magpie/policies
  repositories:
    - https://github.com/openraven/security-rules.git
plugins:
  magpie.aws.discovery:
    enabled: false
    config:
#      proxyRoleConfig:
#        arn: <proxy arn>
#        externalId: <proxy externalID>
      assumedRoles:
      #      - <role arn 1>
      #      - <role arn 2>
      #      - etc...
      services:
#      By default all AWS services are scanned. Uncomment the below lines to enable only select services.
#         - ec2
#         - s3
#         - rds
#         - ecs
#         - vpc
#         See the full list at https://github.com/openraven/magpie
      regions:
#        - aws-global
#        - us-east-2
#        - us-east-1
#        - us-west-1
#        - us-west-2
      ignoredRegions:
        - fips.*
        - us-gov.*
  magpie.gcp.discovery:
    enabled: false
    config:
      services:
  magpie.azure.discovery:
    enabled: true
    config:
      services:
        - storage
        - sql
        - subscriptions
  magpie.json:
    enabled: true
    config:
  magpie.policy.output.json:
    enabled: false
  magpie.policy.output.csv:
    enabled: false
  magpie.policy.output.text:
    enabled: true
  magpie.persist:
    enabled: false
    config:
      hostname: localhost
      port: 5432
      schema: magpie
      databaseName: magpie
      user: magpie
      password: magpie
```

and the relevant  stacktrace : 
```
========== SNIP =========
13:50:42.732 [main] INFO  i.o.m.c.c.s.PolicyAcquisitionServiceImpl - Successfully loaded rule 2cafde41-c4b6-4b74-a7a9-33583cd6ea47
13:50:42.732 [main] INFO  i.o.m.c.c.s.PolicyAcquisitionServiceImpl - Successfully loaded rule 0d828d3c-3704-47af-bf32-3bbe3cdf98f7
13:50:42.732 [main] INFO  i.o.m.c.c.s.PolicyAcquisitionServiceImpl - Successfully loaded rule ff9392b5-b2ce-448a-b1c7-3d25cf8a8c3f
13:50:42.733 [main] INFO  i.o.m.c.c.s.PolicyAcquisitionServiceImpl - Successfully loaded rule b3ff7ae6-32ec-42e9-9261-6cddb63205b2
13:50:42.733 [main] INFO  i.o.m.c.c.s.PolicyAcquisitionServiceImpl - Successfully loaded rule e73d6d97-7bc9-4e70-ab21-1646ebbf8732
13:50:42.733 [main] INFO  i.o.m.c.c.s.PolicyAcquisitionServiceImpl - Successfully loaded rule d78be2e4-5158-45e9-8e3a-67b1d8e41f5d
13:50:42.733 [main] INFO  i.o.m.c.c.s.PolicyAcquisitionServiceImpl - Successfully loaded rule 076b7371-2136-4629-a531-8e9a74f209b7
13:50:42.733 [main] INFO  i.o.m.c.c.s.PolicyAcquisitionServiceImpl - Successfully loaded rule 17a72b4d-cf1a-46f6-8f60-0b9e08894f62
13:50:42.734 [main] INFO  i.o.m.c.c.s.PolicyAcquisitionServiceImpl - Successfully loaded rule 1b05ffa7-606e-4cbc-91f2-696454b0c5d5
13:50:42.734 [main] INFO  i.o.m.c.c.s.PolicyAcquisitionServiceImpl - Successfully loaded rule a33e03e3-d53f-4f76-802b-96274a475bec
13:50:42.734 [main] INFO  i.o.m.c.c.s.PolicyAcquisitionServiceImpl - Successfully loaded rule e7e0e5ab-3fd0-4a8e-b505-f791f0e499ee
13:50:42.735 [main] INFO  i.o.m.c.c.s.PolicyAcquisitionServiceImpl - Successfully loaded rule a9a6c97f-9081-426f-85be-41c485a48b99
13:50:42.735 [main] INFO  i.o.m.c.c.s.PolicyAcquisitionServiceImpl - Successfully loaded rule efa76fbc-1467-4a0b-abf6-d71374c340f1
13:50:42.736 [main] INFO  i.o.m.c.c.s.PolicyAcquisitionServiceImpl - Successfully loaded rule 00b910b7-6dd9-4fb7-bf5d-014d18b6a1a8
13:50:42.736 [main] INFO  i.o.m.c.c.s.PolicyAcquisitionServiceImpl - Successfully loaded rule 38a25426-8499-402f-b8c1-63afe2b07578
13:50:42.736 [main] INFO  i.o.m.c.c.s.PolicyAcquisitionServiceImpl - Successfully loaded rule f16ef4ec-332b-45e1-bbfb-16b9bc9e85cc
13:50:42.737 [main] INFO  i.o.m.c.c.s.PolicyAcquisitionServiceImpl - Successfully loaded rule 4eb29b39-ef5e-48f6-bc63-0984b831e7b8
13:50:42.737 [main] INFO  i.o.m.c.c.s.PolicyAcquisitionServiceImpl - Successfully loaded rule 3c72b7c4-af80-42cf-a227-ccffe86427e6
13:50:42.737 [main] INFO  i.o.m.c.c.s.PolicyAcquisitionServiceImpl - Successfully loaded rule 8b0a36bc-be17-4541-925f-357163ea9c3d
13:50:42.737 [main] INFO  i.o.m.c.c.s.PolicyAcquisitionServiceImpl - Successfully loaded rule 1c2d8884-d4c4-460b-8e98-bd3292d08eb0
13:50:42.737 [main] INFO  i.o.m.c.c.s.PolicyAcquisitionServiceImpl - Successfully loaded rule 84f068c7-7142-4a68-be32-8bd0014a9134
13:50:42.738 [main] INFO  i.o.m.c.c.s.PolicyAcquisitionServiceImpl - Successfully loaded rule deb46000-3ed2-4c8a-afc4-a07e6ad0233d
13:50:42.738 [main] INFO  i.o.m.c.c.s.PolicyAcquisitionServiceImpl - Successfully loaded rule 28aa542d-7573-4f59-be74-65a679478325
13:50:42.738 [main] INFO  i.o.m.c.c.s.PolicyAcquisitionServiceImpl - Successfully loaded rule 6e4b34e3-73d6-481e-a8a9-70611966b836
13:50:42.738 [main] INFO  i.o.m.c.c.s.PolicyAcquisitionServiceImpl - Successfully loaded rule 46f8ec51-3408-4f9d-8d68-f8666de27b09
13:50:42.738 [main] INFO  i.o.m.c.c.s.PolicyAcquisitionServiceImpl - Successfully loaded rule 29bc38e9-6413-4cd4-b9a4-9b6cb21d2e7c
13:50:42.739 [main] INFO  i.o.m.c.c.s.PolicyAcquisitionServiceImpl - Successfully loaded rule 6faa55e6-abba-47d0-ad3b-0e0c23b54465
13:50:42.739 [main] INFO  i.o.m.c.c.s.PolicyAcquisitionServiceImpl - Successfully loaded rule 1acbbe7a-dd6a-4af4-a3e6-7f1d1ebbb66e
13:50:42.739 [main] INFO  i.o.m.c.c.s.PolicyAcquisitionServiceImpl - Successfully loaded rule cfbc750a-48e0-4712-aed0-4abde2dc587c
13:50:42.739 [main] INFO  i.o.m.c.c.s.PolicyAcquisitionServiceImpl - Successfully loaded rule fc80bcf6-34cd-4207-9805-342873951710
13:50:42.739 [main] INFO  i.o.m.c.c.s.PolicyAcquisitionServiceImpl - Successfully loaded rule 56a7d29c-5022-45b1-93d8-107494059fc9
13:50:42.740 [main] INFO  i.o.m.c.c.s.PolicyAcquisitionServiceImpl - Successfully loaded rule ac8c38e5-9259-4154-a6ad-48fa663cbfe8
13:50:42.740 [main] INFO  i.o.m.c.c.s.PolicyAcquisitionServiceImpl - Successfully loaded rule bacfb48f-ac5a-49f2-b829-aabb5328680b
13:50:42.740 [main] INFO  i.o.m.c.c.s.PolicyAcquisitionServiceImpl - Successfully loaded rule a8cb700d-7651-4f97-8124-bf42e6a6c8b9
13:50:42.740 [main] INFO  i.o.m.c.c.s.PolicyAcquisitionServiceImpl - Successfully loaded rule 825a0a30-6ee9-4d62-b889-c5647a4d78a1
13:50:42.741 [main] INFO  i.o.m.c.c.s.PolicyAcquisitionServiceImpl - Successfully loaded rule 70917d30-5350-44fa-9c76-8507a9229e95
13:50:42.741 [main] INFO  i.o.m.c.c.s.PolicyAcquisitionServiceImpl - Successfully loaded rule e7272b89-73e0-4250-aa74-5314d555c917
13:50:42.741 [main] INFO  i.o.m.c.c.s.PolicyAcquisitionServiceImpl - Successfully loaded rule e3aa8bc6-3ccb-4081-ab64-4cd158841779
13:50:42.741 [main] INFO  i.o.m.c.c.s.PolicyAcquisitionServiceImpl - Successfully loaded rule 8a1d92f8-b06b-4fdf-87ff-b660016a44b3
13:50:42.742 [main] INFO  i.o.m.c.c.s.PolicyAcquisitionServiceImpl - Successfully loaded rule b986202a-4007-45d1-9d53-07e3640be33e
13:50:42.742 [main] INFO  i.o.m.c.c.s.PolicyAcquisitionServiceImpl - Successfully loaded rule f5839d08-f236-49ae-9d8c-c584f79578a8
13:50:42.742 [main] INFO  i.o.m.c.c.s.PolicyAcquisitionServiceImpl - Successfully loaded rule 96ccfe84-0465-4e70-9d2a-9ca5dedbf495
13:50:42.742 [main] INFO  i.o.m.c.c.s.PolicyAcquisitionServiceImpl - Successfully loaded rule 41d06ab4-c374-4163-a5b4-7a6904e45f0e
13:50:42.743 [main] INFO  i.o.m.c.c.s.PolicyAcquisitionServiceImpl - Successfully loaded rule 35e1bf60-1df4-45fb-8b8f-f7b6e7bf58da
13:50:42.743 [main] INFO  i.o.m.c.c.s.PolicyAcquisitionServiceImpl - Successfully loaded rule 05719be1-836c-496f-b7fe-d6a7c9756638
13:50:42.743 [main] INFO  i.o.m.c.c.s.PolicyAcquisitionServiceImpl - Successfully loaded rule bb67d8c5-b289-43b0-9e45-0206c8c42155
13:50:42.743 [main] INFO  i.o.m.c.c.s.PolicyAcquisitionServiceImpl - Successfully loaded rule b0e593c6-7283-4bce-8561-f1db88cb462f
13:50:42.743 [main] INFO  i.o.m.c.c.s.PolicyAcquisitionServiceImpl - Successfully loaded rule 75a124e6-1820-4e71-96f0-396b5c4719a5
13:50:42.743 [main] INFO  i.o.m.c.c.s.PolicyAcquisitionServiceImpl - Running git rev-parse HEAD
13:50:42.745 [main] INFO  i.o.m.c.c.s.PolicyAcquisitionServiceImpl - Standard output: 95ca61daa9dfb5f121e57b31a02d704959a386f4

13:50:42.746 [main] INFO  i.o.m.c.c.s.PolicyAcquisitionServiceImpl - Successfully loaded policy: aws-redshift-best-practices
13:50:42.746 [main] INFO  i.o.m.c.c.s.PolicyAcquisitionServiceImpl - Successfully loaded rule 0f842c30-8dc3-4a92-9e74-1971128f8755
13:50:42.746 [main] INFO  i.o.m.c.c.s.PolicyAcquisitionServiceImpl - Successfully loaded rule 2aa03842-b62e-4e17-aad1-112e133d544c
13:50:42.747 [main] INFO  i.o.m.c.c.s.PolicyAcquisitionServiceImpl - Successfully loaded rule d547f850-7542-4aba-a6c8-c14ca0db7835
13:50:42.747 [main] INFO  i.o.m.c.c.s.PolicyAcquisitionServiceImpl - Successfully loaded rule ee05eba9-30f6-467d-a202-c10f02bf111a
13:50:42.747 [main] INFO  i.o.m.c.c.s.PolicyAcquisitionServiceImpl - Successfully loaded rule 65301669-1eef-4fcc-8863-ee6cae5e6e07
13:50:42.747 [main] INFO  i.o.m.c.c.s.PolicyAcquisitionServiceImpl - Successfully loaded rule 5b42f614-045f-4c01-a56d-ba5ea6649679
13:50:42.747 [main] INFO  i.o.m.c.c.s.PolicyAcquisitionServiceImpl - Running git rev-parse HEAD
13:50:42.749 [main] INFO  i.o.m.c.c.s.PolicyAcquisitionServiceImpl - Standard output: 95ca61daa9dfb5f121e57b31a02d704959a386f4

13:50:42.830 [main] INFO  org.hibernate.Version - HHH000412: Hibernate ORM core version [WORKING]
13:50:43.098 [main] INFO  org.reflections.Reflections - Reflections took 239 ms to scan 5 urls, producing 22 keys and 955 values
13:50:43.161 [main] INFO  o.f.c.i.license.VersionPrinter - Flyway Community Edition 7.10.0 by Redgate
Exception in thread "main" org.flywaydb.core.internal.exception.FlywaySqlException: 
Unable to obtain connection from database (jdbc:postgresql://localhost:5432/magpie) for user 'magpie': Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
SQL State  : 08001
Error Code : 0
Message    : Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.

	at org.flywaydb.core.internal.jdbc.JdbcUtils.openConnection(JdbcUtils.java:71)
	at org.flywaydb.core.internal.jdbc.JdbcConnectionFactory.<init>(JdbcConnectionFactory.java:68)
	at org.flywaydb.core.Flyway.execute(Flyway.java:510)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:170)
	at io.openraven.magpie.plugins.persist.migration.FlywayMigrationService.initiateDBMigration(FlywayMigrationService.java:41)
	at io.openraven.magpie.plugins.persist.config.PostgresPersistenceProvider.migratePostgreDB(PostgresPersistenceProvider.java:64)
	at io.openraven.magpie.plugins.persist.config.PostgresPersistenceProvider.getEntityManager(PostgresPersistenceProvider.java:57)
	at io.openraven.magpie.plugins.persist.impl.HibernateAssetsRepoImpl.<init>(HibernateAssetsRepoImpl.java:42)
	at io.openraven.magpie.core.cspm.services.PolicyAnalyzerServiceImpl.init(PolicyAnalyzerServiceImpl.java:48)
	at io.openraven.magpie.core.cspm.services.CspmFacadeImpl.analyze(CspmFacadeImpl.java:50)
	at io.openraven.magpie.cli.Policy.main(Policy.java:46)
Caused by: org.postgresql.util.PSQLException: Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:342)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:54)
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:263)
	at org.postgresql.Driver.makeConnection(Driver.java:443)
	at org.postgresql.Driver.connect(Driver.java:297)
	at org.flywaydb.core.internal.jdbc.DriverDataSource.getConnectionFromDriver(DriverDataSource.java:268)
	at org.flywaydb.core.internal.jdbc.DriverDataSource.getConnection(DriverDataSource.java:232)
	at org.flywaydb.core.internal.jdbc.JdbcUtils.openConnection(JdbcUtils.java:55)
	... 10 more
Caused by: java.net.ConnectException: Connection refused
	at java.base/sun.nio.ch.Net.pollConnect(Native Method)
	at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672)
	at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:542)
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
	at java.base/java.net.Socket.connect(Socket.java:633)
	at org.postgresql.core.PGStream.createSocket(PGStream.java:243)
	at org.postgresql.core.PGStream.<init>(PGStream.java:98)
	at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:132)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:258)
	... 17 more
```

## How to reproduce : 

1. Launch magpie.sh without a postgresql database
2. magpie crashes with the attached stacktrace

## Awaited result :
Magpie does not tries to connect to a postgresql database.

**Comment by kickroot** [comment]
The `magpie.sh` was meant as a shortcut for both `magpie-discovery` and `magpie-policy`.  Magpie Policy requires PG to be running as it needs to query PG via SQL rules.

If you don't wish to run Policy, please use `magpie-discovery` instead.

Thanks!
